version: '3.7'
services:
    api:
        build: .
        depends_on:
            - mongodb
        environment:
            MONGO_URI: mongodb://mongodb:27017/
            MONGO_DB: theamCrmApiDB
            MONGO_DB_TEST: theamCrmApiDB_tests
            NODE_ENV: development
            jwtPrivateKey: theam_crm_api_jwtPrivateKey
            PORT: 3000
        links: [mongodb]
        ports: 
            - "3000:3000"
        command: npm run dev
        volumes:
            - .:/api/
    mongodb:
        image: mongo
        ports:
            - "27017:27017"

