version: '3.7'
services:
    api:
        build: .
        depends_on:
            - mongodb
        environment:
            MONGO_URI: mongodb://mongodb:27017
            NODE_ENV: development
            DEBUG: 'api, db'
            PORT: 3000
        links: [mongodb]
        ports: 
            - "3000:3000"
        command: npm run dev
        volumes:
            - .:/api/
    mongodb:
        image: mongo
        ports:
            - "27017:27017"

